# Generated by Django 5.2.1 on 2025-06-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_rename_email_list_subscriber_list_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attachment',
            field=models.FileField(blank=True, upload_to='email_attachments/'),
        ),
    ]
