# Generated by Django 5.2.1 on 2025-06-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_alter_email_body_emailtracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtracking',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
