# Generated by Django 5.2.1 on 2025-06-22 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
