# Generated by Django 5.2.1 on 2025-06-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='country',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sector',
        ),
    ]
