# Generated by Django 5.2.1 on 2025-06-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraping', '0002_remove_stock_country_remove_stock_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.CharField(blank=True, max_length=50, null=True)),
                ('price_change', models.CharField(blank=True, max_length=50, null=True)),
                ('percent_change', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_close', models.CharField(blank=True, max_length=50, null=True)),
                ('week_52_high', models.CharField(blank=True, max_length=50, null=True)),
                ('week_52_low', models.CharField(blank=True, max_length=50, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=50, null=True)),
                ('pe_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('dividend_yield', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_scraping.stock')),
            ],
        ),
    ]
