# Generated by Django 5.2.1 on 2025-06-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('number_review', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=10)),
                ('country_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('building', models.IntegerField()),
            ],
        ),
    ]
