# Generated by Django 5.2.1 on 2025-06-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_yelp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelp',
            name='building',
            field=models.CharField(max_length=10),
        ),
    ]
